language: node_js

node_js:
- node
- lts/*

notifications:
  email: false

install:
- yarn install

script:
- yarn build

deploy:
- provider: releases
  api_key:
    secure: 0QXVeUIJsH1FBAeA67dm5pNatgkt0fUoNajTeeSql+UKr9eGpuS49/+9dtiXaSdD+MjqAlgEQ3ojz3T35cTrALTN+j63yNn6uiSb62ORvKfG0xiszvpl2s7AY3OKy+Q3BzoL8v+75iQG/p6aSkQ39dkdQwnpBTgyPrsR6/b1qi5pt4zxF8Cu57REsLTMaNrgtSB5X7uPnIsUcIhwHR+JGeYg5z8OkMnQHmuBK4zGmUZVG9ExfmX4g4s63sZDZo7B1j4P1HGrLaUdT09pbuJgyO/DUJpYbC7LF+OGbMTzULVPVltP3U7oEtuaaDIFdvgW+pqtCj8jDv++V1a70dhFMqYIXodTGlw3cwftPLgR2i2QIsblbxaqxhlGwBB3uZCf27ZOEKmPt2cC266uQTEs3uvj8y9B1CwvPew6HY86yj0clkGtThWzCu5v2HJNq5tmSv27XyOh2C5jeXQrWBJntNr14s01lo/VgaMvZGajG9hhoUDuHye4IsQTWWbpWHOUNfSu4Y34nSq34x4TrX2kqXNanwNbDb6WmPS3kwZBrx2xCoHWsUyEv1NCzlrfM0dF60LV007vDkBs7eR+mQc/sQj5zNa7LZate8FMnQxl6PULojGLLk11F2Qp4CvE2A+8a3P5f91BR/5xq7nUudqVKXPxll7hSmzkOZIK6ikQ8vw=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    repo: SiNEXiST/vue-overlay-host
    tags: true
- provider: npm
  email: me@sinexist.de
  api_key:
    secure: CtzTFGWrj6vgBb+33C/j3Fbcs3cp0o9gcV/vl/RnHzM/u+irOKmDKiWpkF/ud5ZDscaOZeRUFt2anRKros3GeMFnjgy2sHflDasTLRxFHPIKiZyT94Bar4t2NWWTxrse12+aivcU4M100oODJNJ2uH1liTPEa0/7A0n01mtd/DkiOfwYGoIi5R0lqTvlbvyRWnVG20V5nu4CgWh7gQSwky33oOzqC+dQ37BurijOdHdA9LFbpecqBvC0Zjm7ajLSPqB1pNpA1h+WfM0XeY5LRCFUkhc7k6HyijEbNeccs6+ea1R62R1nF9ZpBojtlUun6m1rakbF5Hw+IWbH/Fwy7hxFDCTUPuk6o6qRCTx2RP/kEeKuNbAOG5fUqGnKRYuxV6CgeuYe2/0gOv7Z8lb8P1/KQBC7Mlcwi8NLWq/dd9L4fYrkGm4X5pPMLyN4QhevTGigFRqYbAAy4UE3Jxt738zw7DdO0lnuxNnOMeSdeUSJCKN7V0+WGWujHwvnbd7H9xzZyHYzRUU/Rvw3RjThmSUH5R0IsIfyXxcxvY45oettffBlNv8CSKED9RTbrjhFTkKZRANHHNrzaLXxI4MzD3ji2mHuWIH0VR16FeXNRyqzZTiEHggc8AA5N+fCVEPvd8KiZ+SjDzmEMSsODoeGfc5joe2N07HaFxVMcFZfk8M=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    repo: SiNEXiST/vue-overlay-host
